[env:esp32-cam]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = ESPCameraWebServer/partitions.csv
board_build.flash_mode = dio
board_upload.flash_size = 4MB
lib_deps =
    me-no-dev/ESP Async WebServer@^1.2.3
    esphome/esp32-camera@^2.0.4
